== FOSS Business Models
=== Overview:
Understanding the successful business models in the FOSS community will allow students some ground from which to build there own businesses and projects. Knowing why the FOSS business model can make so much money but remain true to the ideals of the community will give insight on where to start for new projects and up and coming businesses. As the community continues to move forward more businesses will adopt FOSS models and having a string understanding of how these work will allow students and professionals to contribute to their growth.

A good backgrounder for instructors on [this topic] is [insert reference], for a deeper understanding see Readings & Resources below.

:toc: macro
toc::[]

=== Prerequisite Knowledge:
Here we list what specific information students should know or skills they should have before you teach this module.

* Assumption 1
* Assumption 2
* etc.

=== Learning objectives:
Here we list the key learning objectives that students should understand at the end.  Where appropriate we will distinguish between beginner, intermediate and advanced levels and/or coding- vs. culture-focused classes.

* learning objective 1 (level)
* learning objective 2 (level)
* learning objective 3 (level, culture)
* etc.

=== Instructional tools:
Here we list any tools or demos that you might use to illustrate concepts that pertain to this topic.
These may include games, videos, simulations, and other multimedia that might help teach this topic.

=== Readings & Resources:
This is a curated list of the most pertinent and relevant learning resources for this topic.
Ex: Links to articles, blog posts, research, or traditional text books.

These links will be curated and constantly updated

.Each resource should have:
* Resource name
* Link or reference information
* Topics / tags (from a curated list), including whether it's better for basic or advanced students and whether it's practical or theory-based
* Description of content that explains when the resource in question would be useful

=== Learning Activities:
This section includes curated links to in-class and out-of-class assignments, projects, and active learning methods that a teacher might use in their classroom.

We see this being two sections:  if your class is participating in an open source project (which we hope everyone is, of course), then you do A.  If not (if, for instance, a regular prof teaching a regular class finds this content and wants to use it in his course), they do B.

A. For classes participating in an open source project:  see module 3 [[all of these need to be built -- this is the framework part of interacting with an open source community]].  Module 3 would be about Topic 1.
B. For classes not participating in an open source project, here are some exercises you might do to reinforce this topic:

.Name of exercise:
* Link to exercise
* Description
* Intended Result
* etc.

=== Teaching Notes:
Additional notes (perhaps from other teachers) on what has worked/not worked in teaching these concepts.
One might want to point out the parts needing emphasis; analogies that work, etc. etc.

=== Assessment of student learning:
How do you measure what the student has learned?
There should be clear mastery criteria defined for each learning objective defined above.

=== ACM Knowlege Area/Knowledge Unit:
What ACM Computing Curricula 2013 knowledge area and units does this activity cover? (http://foss2serve.org/index.php/ACM_Body_of_Knowledge)

=== ACM Topic:
What specific topics are addressed? The Computing Curriucula 2013 provides a list of topics - https://www.acm.org/education/CS2013-final-report.pdf

=== Additional Information  
Author(s):: Names of those who have added or edited content
Source:: Did this come from anywhere else?
License:: License for material
