== FOSS Business Models
=== Overview:
Understanding the successful business models in the FOSS community will allow students some ground from which to build there own businesses and projects. Knowing why the FOSS business model can make so much money but remain true to the ideals of the community will give insight on where to start for new projects and up and coming businesses. As the community continues to move forward more businesses will adopt FOSS models and having a string understanding of how these work will allow students and professionals to contribute to their growth.

A good backgrounder for instructors on [this topic] is [insert reference], for a deeper understanding see Readings & Resources below.

:toc: macro
toc::[]

=== Prerequisite Knowledge:
Here we list what specific information students should know or skills they should have before you teach this module.

* Assumption 1
* Assumption 2
* etc.

=== Learning objectives:
Here we list the key learning objectives that students should understand at the end.  Where appropriate we will distinguish between beginner, intermediate and advanced levels and/or coding- vs. culture-focused classes.

* learning objective 1 (level)
* learning objective 2 (level)
* learning objective 3 (level, culture)
* etc.

=== Instructional tools:
Here we list any tools or demos that you might use to illustrate concepts that pertain to this topic.
These may include games, videos, simulations, and other multimedia that might help teach this topic.

=== Readings & Resources:
This is a curated list of the most pertinent and relevant learning resources for this topic.
Ex: Links to articles, blog posts, research, or traditional text books.

These links will be curated and constantly updated

.Each resource should have:
* Resource name
* Link or reference information
* Topics / tags (from a curated list), including whether it's better for basic or advanced students and whether it's practical or theory-based
* Description of content that explains when the resource in question would be useful

MySQL CEO on 2 Open Source Business Models 
* http://www.heavybit.com/library/video/2013-10-15-marten-mickos
* TAGS
* Marten Mickos discusses the models he has been a part of in his role as CEO of MySQL AB, and Eucalyptus Systems.

Yochai Benkler: The new open-source economics 
* http://www.ted.com/talks/yochai_benkler_on_the_new_open_source_economics#t-1017160
* TAGS
* Brief discussion on the success of open source projects, businesses, and foundations through the efforts of collaborative communities.

OS Business Models:Making Money by Giving it Away 
* http://events.linuxfoundation.org/sites/events/files/slides/lfcs15_hall.pdf
* TAGS 
* Slides from a talk at the Linux Collaboration Summit by Andrew Hall. Basic Overview of the major open source business models and profit gathering methods.

OSS Business Models that Create Value 
* http://www.aabri.com/manuscripts/152159.pdf
* TAGS
* Journal article from the Journal of Management and Marketing Research on 22 OSS revenue models. These models include main business plans and side events and methods of producing revenue.

Apache Sponsorship Page 
* http://www.apache.org/foundation/sponsorship.html
* TAGS
* THe information page on Apache's sponsorship program, where individuals or groups can contribute yearly to Apache. Represents an important revenue model for open source projects.

Running a Tech Conference
* http://blog.pluralsight.com/running-a-tech-conference
* TAGS
* While not directly about FOSS business models, tech conferences can produce a great deal of revenue for open source group, foundations, or companies. This is a simple blog post detailing the basics of running a successful conference.

How Companies Make Money Through Involvement in Open Source Hardware Projects
* http://timreview.ca/article/228
* TAGS
* While not specifically about OSS, this article discusses differences in OSS and OSH projects and companies. In addition, it gives a great viewpoint on the move away from companies that design to communities that design, and companies that deliver final products.

FOSS Business and Sustainability Models
* http://oss-watch.ac.uk/resources/businessandsustainability
* TAGS
* Article from OSS-Watch discussing FOSS models and benefits to businesses that use free or open source software.

The Business of Open Source
* http://oss-watch.ac.uk/resources/businessofopensource  
* TAGS
* Article from OSS-Watch that differentiates open source development from business models, arguing that 'open source' is not a business model. Discusses business models and revenue options.

Business and Sustainability Models Around FOSS
* http://oss-watch.ac.uk/resources/businessworkshop09
* TAGS
* Article from OSS-Watch covering the OSS Watch Business and Sustainability Models workshop 2009. Discusses FOSS fundamentals, culture, and business practices.

Dual-licensing as a Business Model
* http://oss-watch.ac.uk/resources/duallicence2
* TAGS
* Article from OSS-Watch discussing one of the more notable FOSS business models: dual- licensing. References MySQL primarily, as it is the most successful open source company using this model.

Sustainable Open Source
* http://oss-watch.ac.uk/resources/sustainableopensource
* TAGS
* Article from OSS-Watch discussing getting a FOSS project to a sustainable level and maintaining it there. 

The Community Source Development Model
* http://oss-watch.ac.uk/resources/communitysource
* TAGS
* Article from OSS-Watch on an arguably failed business model in the FOSS world. It is important to see all of the successes and failures in the market.

Why There Will Never Be Another Red Hat
* http://techcrunch.com/2014/02/13/please-dont-tell-me-you-want-to-be-the-next-red-hat/
* TAGS
* Article analyzing the successes and failures of Red Hat and how the market has shifted to not allow new companies with this model.

Free's a crowd-funding
* http://www.h-online.com/open/features/Free-s-a-crowd-funding-1847399.html
* TAGS
* Discusses successes and strategies in crowd-funding production models.

Business Models
* http://www.law.washington.edu/lta/swp/Institutions/businessmodels.html
* TAGS
* Brief scholarly article comparing proprietary and open source business models.

Open Source Business Models & Other Articles
* http://drkarlpopp.com/OpenSourceBusinessModels.html#.Vl6LkZNVK1E
* TAGS
* A few good articles on software business, OSS business models and revenue models. As well as other articles and videos.

Wikipedia on Business Models for OSS
* https://en.wikipedia.org/wiki/Business_models_for_open-source_software
* TAGS
* Wikipedia is always a good place to look for open source information!

Selling Free Software
* https://www.gnu.org/philosophy/selling.html
* TAGS
* The GNU/FSF belief and ethics on selling free software and selling other licensed software.



=== Learning Activities:
This section includes curated links to in-class and out-of-class assignments, projects, and active learning methods that a teacher might use in their classroom.

We see this being two sections:  if your class is participating in an open source project (which we hope everyone is, of course), then you do A.  If not (if, for instance, a regular prof teaching a regular class finds this content and wants to use it in his course), they do B.

A. For classes participating in an open source project:  see module 3 [[all of these need to be built -- this is the framework part of interacting with an open source community]].  Module 3 would be about Topic 1.
B. For classes not participating in an open source project, here are some exercises you might do to reinforce this topic:

.Name of exercise:
* Link to exercise
* Description
* Intended Result
* etc.

=== Teaching Notes:
Additional notes (perhaps from other teachers) on what has worked/not worked in teaching these concepts.
One might want to point out the parts needing emphasis; analogies that work, etc. etc.

=== Assessment of student learning:
How do you measure what the student has learned?
There should be clear mastery criteria defined for each learning objective defined above.

=== ACM Knowlege Area/Knowledge Unit:
What ACM Computing Curricula 2013 knowledge area and units does this activity cover? (http://foss2serve.org/index.php/ACM_Body_of_Knowledge)

=== ACM Topic:
What specific topics are addressed? The Computing Curriucula 2013 provides a list of topics - https://www.acm.org/education/CS2013-final-report.pdf

=== Additional Information  
Author(s):: Names of those who have added or edited content
Source:: Did this come from anywhere else?
License:: License for material
